[
  {
    "url": "https://api.github.com/repos/hub4j/github-api/issues/comments/608663715",
    "html_url": "https://github.com/hub4j/github-api/issues/772#issuecomment-608663715",
    "issue_url": "https://api.github.com/repos/hub4j/github-api/issues/772",
    "id": 608663715,
    "node_id": "MDEyOklzc3VlQ29tbWVudDYwODY2MzcxNQ==",
    "user": {
      "login": "bitwiseman",
      "id": 1958953,
      "node_id": "MDQ6VXNlcjE5NTg5NTM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1958953?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bitwiseman",
      "html_url": "https://github.com/bitwiseman",
      "followers_url": "https://api.github.com/users/bitwiseman/followers",
      "following_url": "https://api.github.com/users/bitwiseman/following{/other_user}",
      "gists_url": "https://api.github.com/users/bitwiseman/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bitwiseman/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bitwiseman/subscriptions",
      "organizations_url": "https://api.github.com/users/bitwiseman/orgs",
      "repos_url": "https://api.github.com/users/bitwiseman/repos",
      "events_url": "https://api.github.com/users/bitwiseman/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bitwiseman/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-04-03T21:07:00Z",
    "updated_at": "2020-04-03T21:07:00Z",
    "author_association": "COLLABORATOR",
    "body": "Hm, yeah, data binding errors are pretty rare for this project.  When they do occur they almost always indicate some kind of misuse/mistake on the user's part.  So, it totally makes sense to wrap those in another exception with a helpful message. \r\n\r\nIn this case that message would be something like:\r\n\"Wanted a GHContent object but received an array.  Did you mean to use `getDirectoryContent()`?\"\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/hub4j/github-api/issues/comments/608669056",
    "html_url": "https://github.com/hub4j/github-api/issues/772#issuecomment-608669056",
    "issue_url": "https://api.github.com/repos/hub4j/github-api/issues/772",
    "id": 608669056,
    "node_id": "MDEyOklzc3VlQ29tbWVudDYwODY2OTA1Ng==",
    "user": {
      "login": "LorenzNickel",
      "id": 29959150,
      "node_id": "MDQ6VXNlcjI5OTU5MTUw",
      "avatar_url": "https://avatars.githubusercontent.com/u/29959150?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/LorenzNickel",
      "html_url": "https://github.com/LorenzNickel",
      "followers_url": "https://api.github.com/users/LorenzNickel/followers",
      "following_url": "https://api.github.com/users/LorenzNickel/following{/other_user}",
      "gists_url": "https://api.github.com/users/LorenzNickel/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/LorenzNickel/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/LorenzNickel/subscriptions",
      "organizations_url": "https://api.github.com/users/LorenzNickel/orgs",
      "repos_url": "https://api.github.com/users/LorenzNickel/repos",
      "events_url": "https://api.github.com/users/LorenzNickel/events{/privacy}",
      "received_events_url": "https://api.github.com/users/LorenzNickel/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-04-03T21:13:43Z",
    "updated_at": "2020-04-03T21:13:43Z",
    "author_association": "NONE",
    "body": "That would for sure help. I still don't know how and why this happens and I haven't dived into the code, but the best thing would probably be to not have this method by design for objects on which this method can't be called.\r\nBut as I said, I have neither looked at the code of the repo nor a good understanding of GitHub's API, so probably it's up to you if and how you can improve this.",
    "performed_via_github_app": null
  }
]